version: '3.9'

networks:
  backoffice_network:


services:
  training-service:
    build:
      context: ../training-service
      dockerfile: dev.Dockerfile
    image: training-service-dev
    volumes:
      - ../training-service/src:/app/src
    networks:
      - backoffice_network

  admin-frontend:
    build:
      context: ../web-app
      dockerfile: dev.Dockerfile
    ports:
      - "3001:3000"
    image: admin-frontend-dev
    volumes:
      - ../web-app/src:/app/src
      - ../web-app/index.html:/app/index.html
      - ../web-app/public:/app/public
    networks:
      - backoffice_network

  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    image: api-gateway-express-dev
    environment:
      - DEBUG=true
    ports:
      - "3000:8181"
    volumes:
      - ../api-gateway/src:/app/src
    networks:
      - backoffice_network
    depends_on:
      - training-service
