name: Repository Dispatch
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [run-integration-tests]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
          path: development-setup
      - run: echo ${{ github.event.client_payload.sha }}

      - name: Checkout user-service
        uses: actions/checkout@v3
        with:
          repository: fiufit-taller2-grupo5/user-service
          token: ${{ secrets.PAT }}
          path: user-service

      - name: Change directory to integration-tests and run tests
        run: |
          ls
