name: Repository Dispatch
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [run-integration-tests]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}

      - name: Checkout user-service
        uses: actions/checkout@v2
        with:
          repository: fiufit-taller2-grupo5/user-service
          token: ${{ secrets.PAT }}

      - name: Change directory to integration-tests and run tests
        run: |
          cd user-service/integration-tests
          chmod +x run-tests.sh
          ./run-tests.sh user-service
